server:
  port: 8079   # HTTP (Tomcat) port
management:
  port: 9001

spring:
  # AUTO-CONFIGURATION
  autoconfigure:
    exclude: # Auto-configuration classes to exclude.
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
      - com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration
  application:
     name: sfs-task
  messages: 
     fallbackToSystemLocale: false
     basename: i18n/message   
  http:  
  # 上传文件限制大小
    multipart:  
      maxFileSize: 50Mb  
      maxRequestSize: 50Mb   
  freemarker:
    allowRequestOverride: false
    allowSessionOverride: false
    cache: false
    checkTemplateLocation: true
    contentType: text/html
    exposeRequestAttributes: true
    exposeSessionAttributes: true
    exposeSpringMacroHelpers: true
    requestContextAttribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/  #表示所有的模板文件都放在该目录下
    settings:
        locale: zh_CN
        date_format: yyyy-MM-dd
        time_format: HH:mm:ss
        datetime_format: yyyy-MM-dd HH:mm:ss
        auto_import: /spring.ftl as spring
    resources:
        cachePeriod: 60 # http 缓存过期时间
        staticLocations: # 设置静态资源的存放地址
            - classpath:/static

  dubbo:
     appname: dubbo-demo-ui
     registry: zookeeper://127.0.0.1:2181
     protocol: dubbo
  session:
    store-type: none     #redis/none
    redis:
      flush-mode: on_save
      namespace: fss
  redis:
    host: 10.12.7.17
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 1
    timeout: 0   
logging:
  config: classpath:logback-prd.xml
  path: /data/sfs/xd_task/logs
       
app:
  app_code: sfs_task
  app_name: 金风科技iConnect©SFS 定时任务
  app_module: factory                #factory/devlop
  base_template_path: /home/qmsadm/qmstask/resources/print-templates/
  app_cookie_name: fss_cookie_prd
  expire_time : 604800000  #过期时间

sap:
  serverUrl:
  client:
#oa:
#  http: http://10.12.7.14:80
#  userName: rest
#  password: 123456
#  token: GoldWind-portal-2018
#  groupId: '01000000'  # 设定通讯录的最高级组织编号
oa:
  http: http://toa.goldwind.org
  proxyUrl: https://eis.goldwind.com.cn:443
  userName: rest
  password: 123456
  token: GoldWind-portal-2018
  groupId: '01000000'   # 设定通讯录的最高级组织编号
  #  groupId: '01018505'
  relationship:
    fileName: relationship.txt

po: 
  serverUrl: http://pev.goldwind.com.cn:50000
  userName: gw_eam
  password: hpeam2017

invoice: 
  serverUrl: http://den.goldwind.com.cn:8000
  userName: DNIUQD
  password: gw1234

open:
  userName: SFS
  password: SFS@2020
  url: http://10.12.7.200:7111

file:
  upload: /data/sfs/xd/file
#  fileResource: /home/goldwind/qms/file/
#  resourceUpload: /home/goldwind/qms/file/**
#  mobileUpload: /home/java/apache-tomcat-8.5.38/webapps/ROOT/
#  uploadUrl: http://10.12.10.82:8081
den:
  serverUrl: http://prd.goldwind.com.cn:50000
  username: PIW_WEB_SFS
  password: POD0915pK
jpush:
  appKey: 1a484aeb4848c48a94d64086
  masterSecret: dcaa2ec07f61692c5b9f8cac
BPS:
  serverUrl: http://api-bps.goldwind.com.cn:8080
  app:
    startGWTaskURL: /default/goldwindAPI/startGWTask  #发起流程
    excuteGWTaskURL: /default/goldwindAPI/excuteGWTask  #执行流程
    undoTaskURL: /default/goldwindAPI/undoTask  #获取待办
    queryWorkItem: /default/goldwindAPI/queryWorkItem  #获取代办工作项
    queryProYb: /default/goldwindAPI/queryProYb  #获取已办
    addUser: /default/goldwindAPI/addUser  #添加用户
    terminateTask: /default/goldwindAPI/terminateTask  #终止流程
    getGraphicURL: /default/goldwindAPI/getGraphic?processInstID  #获取流程图
    BackActity: /default/goldwindAPI/BackActity  #退回
    queryApproval: /default/goldwindAPI/queryApproval  #获取审批意见
    getBackActs: /default/goldwindAPI/getBackActs  #获取流程可回退节点
    AssignAfter: /default/goldwindAPI/AssignAfter  #流程加签
    instPro: /default/goldwindAPI/getInstPro  #查询流程基本数据
    queryProStep: /default/goldwindAPI/queryProStep  #查询流程操作历史
    delegateItem: /default/goldwindAPI/delegateItem  #流程转办
    pressTask: /default/goldwindAPI/pressTask  #流程催办
    querySentFlow: /default/goldwindAPI/querySentFlow  #获取已发
    OnestepBackActity: /default/goldwindAPI/OnestepBackActity  #流程单步回退
    appointNextActivities: /default/goldwindAPI/appointNextActivities  #设置某自由活动的后继活动
    getInstProDetail: /default/goldwindAPI/getInstProDetail  #获取流程详情
    withdrawProcess: /default/goldwindAPI/WithdrawProcess  #流程撤回
    withdrawProcessWithoutExecute: /default/goldwindAPI/withdrawProcessWithoutExecute  #流程撤回 申请人下一个工作项未执行前，撤回工作项到申请人
    queryApprovalAndWorkItemName: /default/goldwindAPI/queryApprovalAndWorkItemName  #获取带工作项名称的审批意见
    queryProcesses: /default/goldwindAPI/queryProcesses  #获取流程信息
    renameProInst: /default/goldwindAPI/renameProInst  #修改流程名称
    reladata:  /default/goldwindAPI/getReladata #获取流程相关数据
eis:
  password: sfs#goldwind123
  tokenCode: portal

vue:
  ip : http://sfs.goldwind.com.cn
  port : 80/xd

epm:
  path: http://epm.goldwind.com.cn
fams:
  fileDownUrl: http://fams.goldwind.com.cn/qms/api/file/download?fileKey=
  requestInfo: http://fams.goldwind.com.cn/requestinfo/findbyreqid