server:
  port: 8088   # HTTP (Tomcat) port
management:
  port: 9001

spring:
  # AUTO-CONFIGURATION
  autoconfigure:
    exclude: # Auto-configuration classes to exclude.
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
      - com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration
  application:
     name: demo-ui
  freemarker:
    allowRequestOverride: false
    allowSessionOverride: false
    cache: false
    checkTemplateLocation: true
    contentType: text/html
    exposeRequestAttributes: true
    exposeSessionAttributes: true
    exposeSpringMacroHelpers: true
    requestContextAttribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/  #表示所有的模板文件都放在该目录下
    settings:
        locale: zh_CN
        date_format: yyyy-MM-dd
        time_format: HH:mm:ss
        datetime_format: yyyy-MM-dd HH:mm:ss
        auto_import: /spring.ftl as spring
    resources:
        cachePeriod: 60 # http 缓存过期时间
        staticLocations: # 设置静态资源的存放地址
            - classpath:/static

  dubbo:
     appname: dubbo-demo-ui
     registry: zookeeper://127.0.0.1:2181
     protocol: dubbo
     
logging:
  config: classpath:logback-dev.xml
  path: /usr/java/isp/logs
       
app:
  app_code: demo
  app_name: demo系统
  app_module: devlop                #factory/devlop
  
open:
  userName: EIS_USER
  password: eis#$^10
  url: http://10.12.7.200:7111/
